#!/bin/bash

######################################################################
#
# Site.js v12.6.0 Installer for Linux and macOS.
#
# To use:
#
# wget -qO- https://sitejs.org/install | bash
#
# Copyright (c) 2019 Aral Balkan.
# Released under the AGPL version 3.0 or later license.
# Made with ♥ by Small Technology Foundation (https://small-tech.org)
# Like this? Fund us! (https://small-tech.org/fund-us)
#
######################################################################

set -e
echo
echo " 📡 Downloading Site.js v12.6.0…"

function cleanUp {
  popd > /dev/null
  rm -rf /tmp/sitejs.org
}

# Setup
rm -rf /tmp/sitejs.org
mkdir -p /tmp/sitejs.org
pushd /tmp/sitejs.org > /dev/null

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  # Linux
  wget -q https://sitejs.org/releases/linux/12.6.0.tar.gz
elif [[ "$OSTYPE" == "darwin"* ]]; then
  # macOS
  curl -Os https://sitejs.org/releases/macos/12.6.0.tar.gz
else
  # Unsupported
  echo "\n ❌ Error: this operating system is not supported.\n"
  cleanUp
  exit 1
fi

echo " 📦 Installing…"
gzip -d 12.6.0.tar.gz
tar -xvf 12.6.0.tar > /dev/null 2>&1
sudo mv site /usr/local/bin/

cleanUp

echo " 🎉 Done!"
echo
